# Generated by Django 3.2.6 on 2021-11-01 13:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parser_task', '0002_budget'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='glavbudgetclass',
            options={'verbose_name': 'Справочник главы по бюджетной классификации', 'verbose_name_plural': 'Справочники главы по бюджетной классификации'},
        ),
        migrations.AddField(
            model_name='glavbudgetclass',
            name='budget',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='parser_task.budget', verbose_name='Бюджет'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='glavbudgetclass',
            name='code',
            field=models.CharField(default=0, max_length=3, verbose_name='Код'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='glavbudgetclass',
            name='enddate',
            field=models.DateTimeField(null=True, verbose_name='Дата окончания действия записи'),
        ),
        migrations.AddField(
            model_name='glavbudgetclass',
            name='name',
            field=models.TextField(blank=True, max_length=254, null=True, verbose_name='Сокращенное наименование'),
        ),
        migrations.AddField(
            model_name='glavbudgetclass',
            name='startdate',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата начала действия записи'),
        ),
    ]
