# Generated by Django 3.2.6 on 2021-08-26 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dictionaries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_key', models.IntegerField(verbose_name='Код учереждения')),
                ('name', models.TextField(verbose_name='Наименование организации')),
                ('inn', models.CharField(max_length=10, unique=True, verbose_name='ИНН организации')),
                ('kpp', models.CharField(max_length=9, verbose_name='КПП организации')),
                ('budget_level', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dictionaries.budgetlevel')),
                ('chapter_bk', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dictionaries.chapterbk')),
                ('egrul_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dictionaries.egrulstatus')),
                ('industry_specific_typing', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dictionaries.industryspecifictyping')),
                ('institution_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dictionaries.institutiontype')),
                ('organization_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dictionaries.organizationtype')),
                ('rubpnubp_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dictionaries.rubpnubpstatus')),
            ],
        ),
    ]
