# Generated by Django 3.2.6 on 2021-08-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characteristics_organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='institution_key',
            field=models.IntegerField(unique=True, verbose_name='Код учереждения'),
        ),
    ]
