# Generated by Django 3.2.6 on 2021-08-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование уровня бюджета')),
                ('outside_id', models.CharField(max_length=20, verbose_name='ID источника')),
            ],
        ),
        migrations.CreateModel(
            name='ChapterBK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20, verbose_name='Код главы по БК')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование главы по БК')),
            ],
        ),
        migrations.CreateModel(
            name='EgrulStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование статуса ЕГРЮЛ')),
                ('outside_id', models.CharField(max_length=20, verbose_name='ID источника')),
            ],
        ),
        migrations.CreateModel(
            name='IndustrySpecificTyping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование отраслевой типизации')),
                ('outside_id', models.CharField(max_length=20, verbose_name='ID источника')),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование типа учереждения')),
                ('outside_id', models.CharField(max_length=20, verbose_name='ID источника')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование типа организации')),
                ('outside_id', models.CharField(max_length=20, verbose_name='ID источника')),
            ],
        ),
        migrations.CreateModel(
            name='RubpnubpStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование статуса РУБПНУБП')),
                ('outside_id', models.CharField(max_length=20, verbose_name='ID источника')),
            ],
        ),
    ]
