# Generated by Django 3.2.6 on 2021-08-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetlevel',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Наименование уровня бюджета'),
        ),
        migrations.AlterField(
            model_name='chapterbk',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Наименование главы по БК'),
        ),
        migrations.AlterField(
            model_name='egrulstatus',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Наименование статуса ЕГРЮЛ'),
        ),
        migrations.AlterField(
            model_name='industryspecifictyping',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Наименование отраслевой типизации'),
        ),
        migrations.AlterField(
            model_name='rubpnubpstatus',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Наименование статуса РУБПНУБП'),
        ),
    ]
