# Generated by Django 3.2.6 on 2021-10-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0002_auto_20210827_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutiontype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование типа учреждения'),
        ),
    ]
